version: "3.8"
services:
  openmodelica:
    container_name: openmodelica
    build: ./openmodelica
    tty: true
  opcqlwrapper:
    container_name: opcqlwrapper
    build: git@github.com:AaltoIIC/OPC-UA-GraphQL-Wrapper.git
    ports:
      - 80:8080
