version: "3.8"
services:
  openmodelica:
    container_name: openmodelica
    build: ./openmodelica
  opcqlwrapper:
    container_name: opcqlwrapper
    build: git@github.com:AaltoIIC/OPC-UA-GraphQL-Wrapper.git
